### Verify Mobile Request
# @name verifyMobileNumber
POST {{host}}/Auth_V1/verifyMobileNumber
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "MobileNo": "+880-1704687376"
}

## Response
# {
#     "Data": "52521",
#     "Status": "success",
#     "Message": null
# }