### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Interest On Against Loan Request
# @name getInterestOnAgainstLoan
POST {{host}}/loans_v1/getInterestOnAgainstLoan
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "LoanApplication": {
    "AccountIds": "173915, ",
    "LoanProductCode": "44 ",
    "SuretyAccountIds": "173915, "
  },
  "ByUserId": "{{ByUserId}}",
  "MobileNumber": "{{MobileNumber}}",
  "RolePermissionId": "6,1,1210",
  "UID": "{{ByUserId}}",
  "UserName": "bappy.besra@cccul.com"
}

## Response
{
  "Data": {
    "UserPhoto": null,
    "LoanApplication": null,
    "EligibleLoanAmount": 91350,
    "MaxLoanAmount": 100000,
    "MinimumInstallment": "6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120",
    "IsEligible": true,
    "LoanAccountId": 0,
    "LoanLedgerId": 0,
    "PersonalLedgerId": 0,
    "PersonalLedgerType": 0,
    "LoanNo": null,
    "LoanAccountType": null,
    "Name": null,
    "AppliedAmount": 0,
    "Amount": 0,
    "IssuedAmount": 0,
    "LoanBalance": 0,
    "IssuedDate": null,
    "LastPaidDate": null,
    "InterestRate": 12,
    "Installment": 0,
    "LoanStatus": null,
    "InterestAmount": 0,
    "LPS": 0,
    "LoanFine": 0,
    "LPSRF": 0,
    "ShareFine": 0,
    "LoanType": null,
    "LoanRefund": 0,
    "Days": 0,
    "TerminalID": null,
    "TellerName": null,
    "ModuleCode": null,
    "CardNo": null,
    "SecretKey": null,
    "NameOnCard": null,
    "IsNotEditable": false,
    "IsDefaulter": false,
    "IsSubLedger": false,
    "LoanCollectionType": null,
    "Sort": 0,
    "ApprovalStageCode": null,
    "LedgerCode": null,
    "MonthGap": 0,
    "ApprovedLoanAmount": 0,
    "InterestDays": 0,
    "RefundDueAmount": 0,
    "IsRefundBased": false,
    "RoleID": 0,
    "UserName": null,
    "Password": null,
    "IsActive": false,
    "Flag": 0,
    "RequestTime": null,
    "ResponseStatus": null,
    "IMEI": null,
    "DeviceRegId": null,
    "ConnectionId": null,
    "ByUserId": 0,
    "AccountNo": "",
    "RfidCardNo": "",
    "QR": null,
    "Base64Image": null,
    "OrganizationId": null,
    "CardNumber": null,
    "CardTypeCode": null,
    "CardImage": null,
    "IsVirtual": false,
    "ReturnMessage": null,
    "RolePermissionId": null,
    "FullName": null,
    "PermanentAddressLine1": null,
    "PermanentAddressLine2": null,
    "PermanentAddressLine3": null,
    "PermanentAddressLine4": null,
    "PresentAddressLine1": null,
    "PresentAddressLine2": null,
    "PresentAddressLine3": null,
    "PresentAddressLine4": null,
    "BaseNo": null,
    "Email": null,
    "FathersName": null,
    "MothersName": null,
    "PersonId": 0,
    "SpouseName": null,
    "BloodGroup": null,
    "Gender": null,
    "MaritalStatus": null,
    "MobileNumber": null,
    "Religion": null,
    "Nationality": null,
    "NID": null,
    "PersonPhoto": null,
    "OccupationId": 0,
    "RegisteredMobile": null,
    "LoanId": null,
    "RegisteredStatus": false,
    "UID": 0,
    "CountryCode": null,
    "ImageName": null,
    "ApprovedBy": null,
    "ApprovedDate": null,
    "Stages": 0,
    "PersonIds": null,
    "CreatedBy": null,
    "CreatedDate": null,
    "JobLocation": null,
    "PersonWorkDetails": null,
    "PersonEducationTrainingDetails": null,
    "PersonFamilyDetails": null,
    "PersonAccountsDetails": null,
    "PersonAccountsDetailsXml": null,
    "PersonLoanDetails": null,
    "PersonFamilyLoanDetails": null,
    "ApplicantsEducation": null,
    "PersonAttachments": null,
    "PersonAttachmentsXML": null,
    "ApplicantsEducationXML": null,
    "OwnMembershipNo": null,
    "FatherMembershipNo": null,
    "MotherMembershipNo": null,
    "SpouseMembershipNo": null,
    "HCSNo": null,
    "BirthCertificatesNo": null,
    "ChurchCertificatesNo": null,
    "MemberIdCardNo": null,
    "PassbookNo": null,
    "SavingsBookNo": null,
    "MemberDurationInMonth": null,
    "HDSAccountNo": null,
    "LTSDCertificatesNo": null,
    "ShareDepositAmount": null,
    "SavingsDepositAmount": null,
    "LTDSAccountNo": null,
    "CurrentDueLoan": null,
    "EntryBranchName": null,
    "BranchCode": "-1",
    "PreviousLoanNo": null,
    "RegFormPhoto": null,
    "OnleneRegistrationForm": null,
    "FullNameBengali": null,
    "Parish": null,
    "SpouseAddress": null,
    "SpouseSavingsACNo": null,
    "MotherSavingsACNo": null,
    "FatherSavingsACNo": null,
    "BirthPlace": null,
    "Church": null,
    "PresentAddressLine5": null,
    "PresentAddressLine6": null,
    "PermanentAddressLine5": null,
    "PermanentAddressLine6": null,
    "PrevMembershipNo": null,
    "Remarks": null,
    "OtherMobileNumber": null,
    "EmployeeCode": null,
    "ReligionCode": null,
    "NationalityCode": null,
    "MaritialStatusCode": null,
    "GenderCode": null,
    "ShareAccNo": null,
    "SavingsAccNo": null,
    "AreaName": null,
    "WorkDetXML": null,
    "EducationDetXML": null,
    "FamilyDetXML": null,
    "ProductCode": null,
    "TypeCode": null,
    "Demonimation": null,
    "PassportNo": null,
    "IsNotDetails": 0,
    "OrganizationCode": "0",
    "IsLoadImage": false,
    "HasImage": false,
    "PresentDivision": null,
    "PermanentDivision": null,
    "Occupation": null,
    "OwnSavingsACNo": null,
    "SpouseAge": null,
    "SpousePersAddress": null,
    "RelationWithSpouse": null,
    "OrganizationName": null,
    "BirthDistrictId": 0,
    "BirthDistrictName": null,
    "ParishId": 0,
    "ParishCode": null,
    "ParishName": null,
    "CustId": 0,
    "ChildPersonId": 0,
    "CustName": null,
    "CustCode": null,
    "RelationTypeCode": null,
    "IsAssumeBirthDate": false,
    "IsSmartCounter": false,
    "IsSMSOnly": false,
    "ShareAmountFromMonthsAgo": 0,
    "ProfileImageName": null,
    "DivisionId": 0,
    "DistrictId": 0,
    "PSId": 0,
    "VillageOrAreaId": 0,
    "IsOrganization": false,
    "CompanyName": null,
    "CompanyAddress": null,
    "CompanyLogo": null,
    "OtherEmailAddress": null,
    "CardPhoto": null,
    "IsLate": false,
    "DateOfBirth": "0001-01-01T00:00:00",
    "PermanentAddress": null,
    "PresentAddress": null,
    "ModifiedBy": null,
    "ModifiedDate": null,
    "IsAll": 0,
    "SlNo": 0,
    "FromDate": "0001-01-01T00:00:00",
    "ToDate": "0001-01-01T00:00:00",
    "searchText": "",
    "startRec": 0,
    "pageSize": -1,
    "totalRecords": 0,
    "ActionReason": null,
    "IsLoad": false,
    "ActiveStatus": 0,
    "LastPage": 0
  },
  "Status": "success",
  "Message": null
}