### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Submit Payment Request
# @name submitPayment
POST {{host}}/payments_v2/submitPayment
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
  "UserName": "{{UserName}}",
  "UID": "{{ByUserId}}",
  "ByUserId": "{{ByUserId}}",
  "RolePermissionId": "6,1,1210",
  "PersonId": "{{PersonId}}",
  "EmployeeCode": "{{EmployeeCode}}",
  "MobileNumber": "0",
  "MobileNo": "{{MobileNumber}}",
  "Client": "Web Client",
  "AccHolder": "T-0063599",
  "AccNo": "T-0063599",
  "AccTransfer": "T-0058497",
  "AccType": "16",
  "AccountNo": "T-0063599",
  "AccountNumber": "T-0063599",
  "Amount": 500,
  "CardNo": "0010102700635993",
  "SecretKey": "1458e7509aa5f47ecfb92536e7dd1dc7",
  "NameOnCard": "BAPPY BESRA",
  "Remarks": "3538",
  "OTPRegId": "32508",
  "OTPValue": "332467"
}

## Response
# {
#     "Data": "Your transaction completed successfully with voucher no JVDC202308240001 and remaining balance 275409.00",
#     "Status": "success",
#     "Message": null
# }