### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Relationship Types Request
# @name get_relationship_types
POST {{host}}/recrutements_v1/GetRelationTypes
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
# {
# "UserName": "{{UserName}}",
# "AccountNo": "Not found.",
# "Gender": "M",
# "MobileNo": "{{MobileNumber}}",
# "MobileNumber": "{{MobileNumber}}",
# "RolePermissionId": "6,1,1209,1210",
# "ByUserId": 10,
# "UID": "{{ByUserId}}",
# "EmployeeCode": "{{EmployeeCode}}",
# "PersonId": 12345
# }

## Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }