### Login Request
# @name login
POST {{host}}/Auth_V2/UserLogin
Content-Type: application/json
Accept: application/json

## Request Body
{
  "UserName": "{{UserName}}",
  "Password": "{{EncryptedPassword}}"
}

### Set Token
@token = {{login.response.headers.Token}}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Get Thanas Request
# @name get_thanas
POST {{host}}/recrutements_v1/GetAddress
Content-Type: application/json
Accept: application/json
Token: {{token}}

## Request Body
{
    "DivisionId": 0,
    "DistrictId": 1,
    "PSId": 0,
    "VillageOrAreaId": 0
}

## Response
# {
#     "Data": "find_out",
#     "Status": "success",
#     "Message": null
# }